
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# Discovery locator (disabled)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# JWT secret (must match user-service)
jwt.secret=bXlTdXBlclNlY3JldEtleVRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZw==

# GLOBAL CORS (FIXED)
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowCredentials=true

# Default filters
spring.cloud.gateway.server.webflux.default-filters=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# USER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/public/**,/api/users/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

# PRODUCT SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

# ORDER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.server.webflux.routes[2].predicates[1]=Method=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.routes[2].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST