spring.application.name=hospital-service


server.port=8083


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_core
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT 
jwt.secret=bXlTdXBlclNlY3JldEtleVRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZw==
jwt.expiration=86400000

# CORS  allow React dev server
spring.web.cors.allowed-origins=http://localhost:3000


openai.api.key=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


gemini.api.key=AIzaSyAZ09Eis-W-xGe9mNeL6rGI7BlnFJFWbkQ

#  Logging 
logging.level.com.service.auth=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG



