spring.application.name=hospital-service


server.port=8083

spring.config.import=optional:file:hospital-service/.env[.properties]
# spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url= ${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT 
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${86400000}

# CORS  allow React dev server
spring.web.cors.allowed-origins=${DEV_SERVER}


# API KEY 
gemini.api.key=${GMINI_API_KEY}

#  Logging 
logging.level.com.service.auth=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG



